
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - /opt/docker-data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    container_name: mariadb
    networks:
      - mariadb
networks:
  mariadb:
    name: mariadb
