
services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - /opt/docker-data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
