

networks:
  modwp:
  mariadb:
    external: true
  proxy:
    external: true

services:
  mod_wordpress_phpfpm:
    networks:
      - modwp
      - mariadb
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: modguild
      WORDPRESS_DB_NAME: modguild
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: wp_
      DOCKER_COMPOSE_YML_LOCAION: ${pwd}
    volumes:
      - ./_data:/var/www/html
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    container_name: modguild_phpfpm
    build:
      context: ./docker/php
  mod_wordpress_nginx:
    networks:
      - modwp
      - proxy
    image: nginx:latest
    command: /bin/sh -c "userdel www-data ; usermod -u $$UID nginx && groupmod -g $$GID nginx && /docker-entrypoint.sh nginx -g 'daemon off;'"
    restart: always
    environment:
      UID: 33
      GID: 33
    volumes:
      - ./_data:/var/www/html
      - ./wordpress_nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_cache:/var/cache/nginx
      - ./nginx.pid:/var/run
volumes:
  nginx_cache:
